
import java.sql.*;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author acer-pc
 */
public class adddoc extends javax.swing.JFrame {
    Connection conn=null;
    PreparedStatement stt=null;
    ResultSet rs=null;

    /**
     * Creates new form addvoter
     */
    public adddoc() {
        initComponents();
    }
    public void shi(){
        if(mor.isSelected() && eve.isSelected()){
            try{
                Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/hms","root", "");
            Statement stt = conn.createStatement();

            PreparedStatement updateemp = conn.prepareStatement("INSERT INTO doctime (docid,shift,time) VALUES (?,?,?)");
            updateemp.setString(1,ID.getText());
            updateemp.setString(2,"Morning");
            updateemp.setString(3,"10 AM to 1 PM");
            updateemp.executeUpdate();
            
            conn=DriverManager.getConnection("jdbc:mysql://localhost/hms","root", "");
            updateemp = conn.prepareStatement("INSERT INTO doctime (docid,shift,time) VALUES (?,?,?)");
            updateemp.setString(1,ID.getText());
            updateemp.setString(2,"Evening");
            updateemp.setString(3,"6 PM to 10 PM");
            updateemp.executeUpdate();
            
            
            
            }
            catch(Exception e){
               JOptionPane.showMessageDialog(null, "Something is Wrong! Please Try Again"); 
            }
            
        }
        else if(mor.isSelected()){
        try{
                Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/hms","root", "");
            Statement stt = conn.createStatement();

            PreparedStatement updateemp = conn.prepareStatement("INSERT INTO doctime (docid,shift,time) VALUES (?,?,?)");
            updateemp.setString(1,ID.getText());
            updateemp.setString(2,"Morning");
            updateemp.setString(3,"10 AM to 1 PM");
            updateemp.executeUpdate();
        }
        catch(Exception e){
               JOptionPane.showMessageDialog(null, "Something is Wrong! Please Try Again"); 
            }
    }
        else{
            try{
                Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/hms","root", "");
            Statement stt = conn.createStatement();

            PreparedStatement updateemp = conn.prepareStatement("INSERT INTO doctime (docid,shift,time) VALUES (?,?,?)");
            updateemp.setString(1,ID.getText());
            updateemp.setString(2,"Evening");
            updateemp.setString(3,"6 PM to 10 PM");
            updateemp.executeUpdate();
        }
        catch(Exception e){
               JOptionPane.showMessageDialog(null, "Something is Wrong! Please Try Again"); 
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        Name = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        PASSWORD = new javax.swing.JTextField();
        eve1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        visit = new javax.swing.JTextField();
        com = new javax.swing.JComboBox<>();
        eve = new javax.swing.JCheckBox();
        phone = new javax.swing.JTextField();
        mor = new javax.swing.JCheckBox();
        jLabel18 = new javax.swing.JLabel();
        mor1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(940, 540));
        jPanel1.setPreferredSize(new java.awt.Dimension(940, 540));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Create Doctor Account");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, -1, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Doctor ID:-");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Name:-");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, -1, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Visit:-");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 330, -1, -1));
        jPanel1.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 206, 30));
        jPanel1.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 206, 30));

        jButton1.setBackground(new java.awt.Color(0, 153, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_tick_box_26px.png"))); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 430, -1, 46));

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_delete_26px.png"))); // NOI18N
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 430, -1, 46));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Password:-");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 85, -1));
        jPanel1.add(PASSWORD, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 206, 30));

        eve1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        eve1.setText("6 PM to 10 PM");
        jPanel1.add(eve1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 230, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer-pc\\Pictures\\hms\\Annotation 2020-03-28 011256.png")); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 940, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Speciality:-");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 270, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Phone:-");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, -1, -1));
        jPanel1.add(visit, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 350, 206, 30));

        com.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        com.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Anesthesiology", "Cardiac & Vascular Surgery", "Cardiology", "Child Development", "Clinical Hematology", "Colorectal & Laparoscopic Surgery", "Dental & Maxillofacial Surgery", "Dermatology", "Endocrinology", "ENT, Head & Neck Surgery", "Executive Health Check Up", "Gastroenterology", "General Surgery", "Internal Medicine", "Neurosurgery", "Orthopedics", "Psychiatry" }));
        jPanel1.add(com, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 290, 210, 30));

        eve.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        eve.setText("Evening");
        jPanel1.add(eve, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 200, -1, -1));
        jPanel1.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 206, 30));

        mor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mor.setText("Morning");
        jPanel1.add(mor, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 200, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Shift:-");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 170, -1, -1));

        mor1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mor1.setText("10 AM to 1 PM");
        jPanel1.add(mor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 230, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setVisible(false);
        admin a=new admin();
        a.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/hms","root", "");
            Statement stt = conn.createStatement();

            PreparedStatement updateemp = conn.prepareStatement("INSERT INTO docinfo (docid,name,speciality,phone,visit) VALUES (?,?,?,?,?)");
            updateemp.setString(1,ID.getText());
            updateemp.setString(2,Name.getText());
            updateemp.setString(3,com.getSelectedItem().toString());
            updateemp.setString(4,phone.getText());
            updateemp.setString(5,visit.getText());
            updateemp.executeUpdate();
            
            conn=DriverManager.getConnection("jdbc:mysql://localhost/hms","root", "");
            updateemp = conn.prepareStatement("INSERT INTO doclogin (docid,pass) VALUES (?,?)");
            updateemp.setString(1,ID.getText());
            updateemp.setString(2,PASSWORD.getText());
            updateemp.executeUpdate();
            conn.close();
            shi();
            JOptionPane.showMessageDialog(null, "Data Inserted Successfully");
            
            
            ID.setText("");
            Name.setText("");
            PASSWORD.setText("");
            visit.setText("");
            phone.setText("");
            com.setSelectedItem("None");
        }
        catch(Exception e){
           JOptionPane.showMessageDialog(null, "Something is Wrong! Please Try Again"); 
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addrec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addrec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addrec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addrec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addrec().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ID;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField PASSWORD;
    private javax.swing.JComboBox<String> com;
    private javax.swing.JCheckBox eve;
    private javax.swing.JLabel eve1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JCheckBox mor;
    private javax.swing.JLabel mor1;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField visit;
    // End of variables declaration//GEN-END:variables
}
